[package]
name = "comicviewerj3"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "comicviewerj3_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2.4.3"
tauri-plugin-log = "2"
tauri-plugin-dialog = "2"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

specta = { version = "=2.0.0-rc.25", features = ["derive", "serde_json"] }
tauri-specta = { version = "=2.0.0-rc.25", features = ["typescript"] }
specta-typescript = "=0.0.12"

rayon = "1.12.0"
anyhow = "1.0.104"
log = "0.4.33"
chrono = "0.4.45"
dashmap = "6.2.1"
maplit = "1.0.2"
regex = "1.13.1"

vibrato = "0.5.2"
wana_kana = "5.0.0"
zstd = "0.13.3"
csv = "1.4.0"
rustmigemo = { git = "https://github.com/oguna/rustmigemo", tag = "v0.1.7-rc.0" }
encoding_rs = "0.8.35"
unicode-normalization = "0.1.25"
kanaria = "0.2.0"

#[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-window-state = "2"

[build-dependencies]
tauri-build = { version = "2", features = [] }
reqwest = { version = "0.13.4", features = ["blocking"] }
xz2 = "0.1.7"
tar = "0.4.46"
flate2 = "1.1.9"
zip = "8.6.0"

