// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Rust側の初期化 (ほかのコマンドを使用する前に呼ぶ) */
	init: () => typedError<null, string>(__TAURI_INVOKE("init")),
	/**  アプリ終了 */
	exitApp: () => __TAURI_INVOKE<void>("exit_app"),
	/**  タブ作成 (絶対パス) */
	createTab: (path: string) => typedError<TabInfoUI, string>(__TAURI_INVOKE("create_tab", { path })),
	/**  タブ作成 (指定タブと同じパス) */
	cloneTab: (tabId: number) => typedError<TabInfoUI, string>(__TAURI_INVOKE("clone_tab", { tabId })),
	/**  タブ作成 (指定タブの子ディレクトリ) */
	cloneTabChildDir: (tabId: number, fileId: string) => typedError<TabInfoUI, string>(__TAURI_INVOKE("clone_tab_child_dir", { tabId, fileId })),
	/**  タブ作成 (指定タブの親ディレクトリ) */
	cloneTabParentDir: (tabId: number) => typedError<TabInfoUI, string>(__TAURI_INVOKE("clone_tab_parent_dir", { tabId })),
	/**  タブ削除 */
	removeTab: (tabId: number) => typedError<null, string>(__TAURI_INVOKE("remove_tab", { tabId })),
	/**  タブ一覧 */
	getTabs: () => __TAURI_INVOKE<TabInfoUI[]>("get_tabs"),
	/**  ファイル一覧取得 (ソート後やファイル状態が更新された後で呼ぶ) */
	getDirEntries: (tabId: number) => typedError<DirEntryUI[], string>(__TAURI_INVOKE("get_dir_entries", { tabId })),
	/**  ファイル情報まとめて取得 */
	getFileInfos: (tabId: number, fileIds: string[]) => typedError<FileInfoUI[], string>(__TAURI_INVOKE("get_file_infos", { tabId, fileIds })),
	/**  ファイル一覧をソートする (まだソートできない場合は false を返す) */
	sortFiles: (tabId: number, sortCondition: SortCondition) => typedError<boolean, string>(__TAURI_INVOKE("sort_files", { tabId, sortCondition })),
	/**  ローマ字入力からファイル名をあいまい検索 */
	searchNextFilename: (tabId: number, startIndex: number, romaji: string, reverse: boolean) => typedError<FileSearchResult, string>(__TAURI_INVOKE("search_next_filename", { tabId, startIndex, romaji, reverse })),
	/**  設定取得 */
	loadPreferences: () => typedError<AppPreferences, string>(__TAURI_INVOKE("load_preferences")),
	/**  設定保存 */
	savePreferences: (preferences: AppPreferences) => typedError<null, string>(__TAURI_INVOKE("save_preferences", { preferences })),
};

/* Types */
export type AppPreferences = {
	debug_filename_search_sleep_ms: number,
};

/**  UIへ返すファイル一覧の要素 */
export type DirEntryUI = {
	file_id: number,
	is_dir: boolean,
	name: string,
};

export type Either<A, B> = ({ Left: A }) & { Right?: never } | ({ Right: B }) & { Left?: never };

/**  UIに返す詳細ファイル情報 */
export type FileInfoUI = {
	metadata: Either<string, FileMetadata>,
};

/**  詳細ファイル情報のメタデータ */
export type FileMetadata = {
	size: number | null,
	modified: number | null,
	accessed: number | null,
	created: number | null,
};

/**  ファイル検索結果 */
export type FileSearchResult = 
/**  見つかった */
{ type: "Success"; index: number; name: string; match_str: string } | 
/**  形態素解析が終わっていない */
{ type: "FailNoMatch" } | 
/**  見つからなかった */
{ type: "FailNoCache" } | 
/**  状態が変わったのでキャンセル */
{ type: "Canceled" };

export type SortCondition = {
	sort_type: SortType,
	/**  昇順: true */
	asc: boolean,
};

/**  ファイルのソート条件 */
export type SortType = 
/**  名前でソート */
{ type: "Name" } | 
/**  拡張子でソート */
{ type: "Ext" } | 
/**  ファイルサイズでソート */
{ type: "Size" } | 
/**  更新日時でソート */
{ type: "Time" };

export type TabInfoUI = {
	id: number,
	path: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

