// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  アプリ終了 */
	exitApp: () => __TAURI_INVOKE<void>("exit_app"),
	/**  Rust側の初期化 (ほかのコマンドを使用する前に呼ぶ) */
	init: () => typedError<null, string>(__TAURI_INVOKE("init")),
	/**  新規タブ作成 */
	createTab: () => __TAURI_INVOKE<number>("create_tab"),
	/**  タブ削除 */
	removeTab: (tabId: number) => typedError<null, string>(__TAURI_INVOKE("remove_tab", { tabId })),
	/**  タブ一覧 */
	getTabIds: () => __TAURI_INVOKE<number[]>("get_tab_ids"),
	/**  ディレクトリ中のファイル一覧を読み込む */
	readDirEntries: (tabId: number, path: string) => typedError<DirEntry[], string>(__TAURI_INVOKE("read_dir_entries", { tabId, path })),
	/**  ファイル一覧取得 (ソート後やファイル状態が更新された後で呼ぶ) */
	getDirEntries: (tabId: number) => typedError<DirEntry[], string>(__TAURI_INVOKE("get_dir_entries", { tabId })),
	/**  ファイル情報取得 */
	getFileInfo: (tabId: number, fileId: string) => typedError<FileInfo, string>(__TAURI_INVOKE("get_file_info", { tabId, fileId })),
	/**  ファイル一覧をソートする */
	sortFiles: (tabId: number, sortType: SortType) => __TAURI_INVOKE<boolean>("sort_files", { tabId, sortType }),
	/**  ローマ字入力からファイル名をあいまい検索 */
	searchNextFilename: (tabId: number, startIndex: number, romaji: string, reverse: boolean) => typedError<FileSearchResult, string>(__TAURI_INVOKE("search_next_filename", { tabId, startIndex, romaji, reverse })),
};

/* Types */
/**  UIへ返すファイル一覧の要素 */
export type DirEntry = {
	id: number,
	name: string,
};

/**  UIに返す詳細ファイル情報 */
export type FileInfo = {
	name: string,
	metadata: FileMetadata | null,
};

/**  詳細ファイル情報のメタデータ */
export type FileMetadata = {
	is_dir: boolean,
	size: number | null,
	modified: number | null,
	accessed: number | null,
	created: number | null,
};

/**  ファイル検索結果 */
export type FileSearchResult = 
/**  見つかった */
{ type: "Success"; index: number; name: string; match_str: string } | 
/**  形態素解析が終わっていない */
{ type: "FailNoMatch" } | 
/**  見つからなかった */
{ type: "FailNoCache" };

/**  ファイルのソート条件 */
export type SortType = 
/**  名前でソート */
{ type: "Name"; asc: boolean } | 
/**  拡張子でソート */
{ type: "Ext"; asc: boolean } | 
/**  ファイルサイズでソート */
{ type: "Size"; asc: boolean } | 
/**  更新日時でソート */
{ type: "Time"; asc: boolean };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

