// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Rust側の初期化 (ほかのコマンドを使用する前に呼ぶ) */
	init: () => typedError<AppConstants, string>(__TAURI_INVOKE("init")),
	/**  アプリ終了 */
	exitApp: () => __TAURI_INVOKE<void>("exit_app"),
	/**  外部プログラム起動 */
	invokeProgram: (currentDir: string, program: string, args: string[]) => typedError<InvokeProgramResult, string>(__TAURI_INVOKE("invoke_program", { currentDir, program, args })),
	/**  フルスクリーン */
	setFullscreen: (fullscreen: boolean) => __TAURI_INVOKE<void>("set_fullscreen", { fullscreen }),
	/**  タスク中断 */
	cancelTask: (taskId: number) => __TAURI_INVOKE<void>("cancel_task", { taskId }),
	/**  コピー、移動時の確認に対する応答 */
	respondToTask: (taskId: number, response: TaskResponse) => __TAURI_INVOKE<void>("respond_to_task", { taskId, response }),
	/**  ダミー */
	dummy: (fileNotify: FileUpdateNotifyEvent, prepare: GetFilesPropertyNotifyEvent, remove: RemoveFilesNotifyEvent, copyMove: FilePasteNotifyEvent, confirm: FilePasteConfirmEvent) => __TAURI_INVOKE<void>("dummy", { fileNotify, prepare, remove, copyMove, confirm }),
	/**  タブ作成 (絶対パス) */
	createTab: (path: string) => typedError<Either<CreateTabError, TabInfoUI>, string>(__TAURI_INVOKE("create_tab", { path })),
	/**  タブ作成 (指定タブと同じパス) */
	cloneTab: (tabId: number) => typedError<Either<CreateTabError, TabInfoUI>, string>(__TAURI_INVOKE("clone_tab", { tabId })),
	/**  タブ作成 (指定タブの子ディレクトリ) */
	cloneTabChildDir: (tabId: number, fileId: string) => typedError<Either<CreateTabError, TabInfoUI>, string>(__TAURI_INVOKE("clone_tab_child_dir", { tabId, fileId })),
	/**  タブ作成 (指定タブの親ディレクトリ) */
	cloneTabParentDir: (tabId: number) => typedError<Either<CreateTabError, TabInfoUI>, string>(__TAURI_INVOKE("clone_tab_parent_dir", { tabId })),
	/**  タブ作成 (指定タブの隣のディレクトリ) */
	cloneTabSiblingDir: (tabId: number, moveNext: boolean) => typedError<Either<CreateTabError, TabInfoUI>, string>(__TAURI_INVOKE("clone_tab_sibling_dir", { tabId, moveNext })),
	/**  タブ削除 */
	removeTab: (tabId: number) => typedError<null, string>(__TAURI_INVOKE("remove_tab", { tabId })),
	/**  タブ一覧 */
	getTabs: () => __TAURI_INVOKE<TabInfoUI[]>("get_tabs"),
	/**  ファイル一覧取得 (ソート後やファイル状態が更新された後で呼ぶ) */
	getDirEntries: (tabId: number) => typedError<DirEntryUI[], string>(__TAURI_INVOKE("get_dir_entries", { tabId })),
	/**  ファイル情報まとめて取得 */
	getFileInfos: (tabId: number, fileIds: string[]) => typedError<FileInfoUI[], string>(__TAURI_INVOKE("get_file_infos", { tabId, fileIds })),
	/**  ファイル一覧をソートする (まだソートできない場合は false を返す) */
	sortFiles: (tabId: number, sortCondition: SortCondition) => typedError<boolean, string>(__TAURI_INVOKE("sort_files", { tabId, sortCondition })),
	/**  新規ファイル */
	createFile: (tabId: number, name: string) => typedError<FileOpResult, string>(__TAURI_INVOKE("create_file", { tabId, name })),
	/**  新規ディレクトリ */
	createDirectory: (tabId: number, name: string) => typedError<FileOpResult, string>(__TAURI_INVOKE("create_directory", { tabId, name })),
	/**  リネーム */
	renameFile: (tabId: number, fileId: string, name: string) => typedError<FileOpResult, string>(__TAURI_INVOKE("rename_file", { tabId, fileId, name })),
	/**  削除 */
	removeFiles: (tabId: number, fileIds: string[], taskId: number) => typedError<null, string>(__TAURI_INVOKE("remove_files", { tabId, fileIds, taskId })),
	/**
	 *  ファイル／ディレクトリの情報取得
	 *  途中経過と最終結果は [`GetFilesPropertyNotifyEvent`] でUIに通知される
	 */
	getFilesProperty: (tabId: number, fileIds: string[], taskId: number) => typedError<null, string>(__TAURI_INVOKE("get_files_property", { tabId, fileIds, taskId })),
	/**  ファイルを Ctrl+X,Ctrl+C */
	fileCutOrCopyToClipboard: (mode: MoveOrCopy, tabId: number, fileIds: string[]) => typedError<null, string>(__TAURI_INVOKE("file_cut_or_copy_to_clipboard", { mode, tabId, fileIds })),
	/**  ファイルを Ctrl+V */
	filePasteFromClipboard: (taskId: number, tabId: number) => typedError<ClipboardPasteResult, string>(__TAURI_INVOKE("file_paste_from_clipboard", { taskId, tabId })),
	/**  ローマ字入力からファイル名をあいまい検索 */
	searchNextFilename: (tabId: number, startIndex: number, romaji: string, reverse: boolean) => typedError<FileSearchResult, string>(__TAURI_INVOKE("search_next_filename", { tabId, startIndex, romaji, reverse })),
	/**  画像のサイズを取得 */
	getImageSize: (tabId: number, fileId: string) => typedError<{
	width: number,
	height: number,
} | null, string>(__TAURI_INVOKE("get_image_size", { tabId, fileId })),
	/**  画像ファイルのサムネイルを取得 */
	getThumbnail: (tabId: number, fileId: string, size: number) => typedError<GetThumbnailResult, string>(__TAURI_INVOKE("get_thumbnail", { tabId, fileId, size })),
	/**  リサイズした画像ファイルを取得する */
	getResizedImg: (tabId: number, fileId: string, targetSize: Dimension) => typedError<GetResizedImgResult, string>(__TAURI_INVOKE("get_resized_img", { tabId, fileId, targetSize })),
	/**  設定取得 */
	loadPreferences: () => typedError<AppPreferences, string>(__TAURI_INVOKE("load_preferences")),
	/**  設定保存 */
	savePreferences: (preferences: AppPreferences) => typedError<null, string>(__TAURI_INVOKE("save_preferences", { preferences })),
};

/* Types */
/**  アプリ初期化時にRustからUIに渡す定数情報 */
export type AppConstants = {
	/**  ファイル更新イベントのID */
	event_name_file_updaet: string,
	event_name_get_files_property: string,
	event_name_file_delete_progress: string,
	event_name_file_paste_confirm: string,
	event_name_file_paste_progress_notify: string,
};

/**  Rust側で保持するアプリ設定 */
export type AppPreferences = {
	/**  ファイル名検索するときスリープする */
	debug_filename_search_sleep_ms: number,
	/**  ファイル削除時にスリープする */
	debug_file_op_sleep_ms: number,
	/**  ファイル名ソート時の文字比較方法 */
	filename_cmp: FilenameCmpType,
	/**  ファイル名ソート時、先頭の数字を数字として比較 */
	filename_cmp_by_digit: boolean,
	/**
	 *  ファイル名ソート時のCollator設定 (icu_collator::options::Strength)
	 *  'Primary', 'Secondary', 'Tertiary', 'Quaternary', 'Identical'
	 */
	filename_sort_strength: string,
	/**  サムネイルファイル削除期限 */
	thumbnail_expiration_days: number,
	/**  サムネイル作成同時実行数 */
	thumbnail_command_limit: number,
	/**  画像リサイズ同時実行数 */
	resize_image_command_limit: number,
	/**  画像リサイズ時の画質設定 */
	resize_image_config: ResizeImageConfig,
	/**  リサイズ画像ファイル削除期限 */
	resized_image_expiration_minutes: number,
	/**  デフォルト値。UI側で参照のため (UI側ではnullにならない) */
	default: AppPreferences | null,
};

/**  クリップボードからファイルをペーストした結果 */
export type ClipboardPasteResult = 
/**  クリップボードにファイルがなかったので何もしない */
{ type: "NoFiles" } | 
/**  不正なパスなので何もしない */
{ type: "InvalidPath"; path: string } | 
/**  Cutされた結果を移動中 */
{ type: "ProgressMove" } | 
/**  Copyされた結果をコピー中 */
{ type: "ProgressCopy" };

/**
 *  [`create_tab()`](crate::commands::tabs::create_tab) 、`clone_*()` コマンドの失敗情報
 * 
 *  (指定されたディレクトリがないなど、システムエラーでない場合)
 */
export type CreateTabError = {
	msg: string,
};

/**  width, height を持つ構造体 */
export type Dimension = {
	width: number,
	height: number,
};

/**  UIへ返すファイル一覧の要素 */
export type DirEntryUI = {
	file_id: number,
	is_dir: boolean,
	is_symlink: boolean,
	name: string,
};

/**  2つの型のどちらか片方だけ保持するための構造体 */
export type Either<A, B> = ({ Left: A }) & { Right?: never } | ({ Right: B }) & { Left?: never };

/**  UIに返す詳細ファイル情報 */
export type FileInfoUI = {
	file_id: number,
	metadata: Either<string, FileMetadata>,
};

/**  [`FileInfoUI`] に含まれるメタデータ */
export type FileMetadata = {
	size: number | null,
	modified: number | null,
	accessed: number | null,
	created: number | null,
};

/**
 *  ファイル操作(
 *  [`create_file()`](crate::commands::fs::create_file),
 *  [`create_directory()`](crate::commands::fs::create_directory),
 *  [`rename_file()`](crate::commands::fs::rename_file),
 *  )の結果
 */
export type FileOpResult = 
/**  成功 */
{ type: "Success" } | 
/**  不正なファイル名 */
{ type: "InvalidFilename" } | 
/**  すでに存在している */
{ type: "AlreadyExists" } | 
/**  システムエラー以外の失敗 */
{ type: "Fail"; error_msg: string };

/**  ファイルコピー、移動時の重複ファイル処理確認イベント */
export type FilePasteConfirmEvent = {
	task_id: number,
	/**  元パス */
	src_path: string,
	/**  先パス */
	dst_dir: string,
	/**  ファイルか */
	is_file: boolean,
};

/**  ファイルコピー、移動 ([`file_paste_from_clipboard()`](crate::commands::fs_clipboard::file_paste_from_clipboard)) の途中経過を通知するイベント構造体 */
export type FilePasteNotifyEvent = {
	task_id: number,
	is_copy: boolean,
	head: TaskEventHeader,
	progress: TaskEventFileProgress,
};

/**  ファイル検索([`search_next_filename()`](crate::commands::search::search_next_filename))の結果 */
export type FileSearchResult = 
/**  見つかった */
{ type: "Success"; 
/**  ファイルのインデックス (ソートされたファイル一覧の中の) */
index: number; 
/**  ファイル名 */
name: string; 
/**  ファイル名の中のマッチした部分 */
match_str: string } | 
/**  形態素解析が終わっていない */
{ type: "FailNoMatch" } | 
/**  見つからなかった */
{ type: "FailNoCache" } | 
/**  状態が変わったのでキャンセル */
{ type: "Canceled" };

/**  ファイル更新をUIに通知する (タブ作成後からタブ削除までの間の変更を通知する) */
export type FileUpdateNotifyEvent = {
	tab_id: number,
	file_id: number | null,
};

/**  ファイル名ソート時の文字比較方法 ([`AppPreferences`]の要素) */
export type FilenameCmpType = 
/**  Unicode文字コード順 */
{ type: "Unicode" } | 
/**  Shift-JIS */
{ type: "Sjis" } | 
/**  自然 */
{ type: "Icu" };

/**  ディレクトリの状態取得 ([`get_files_property()`](crate::commands::fs::get_files_property)) の途中経過を通知するイベント構造体 */
export type GetFilesPropertyNotifyEvent = {
	task_id: number,
	head: TaskEventHeader,
	progress: TaskEventFileProgress,
};

/**  [`get_resized_img()`](crate::commands::images::get_resized_img) コマンドの結果 */
export type GetResizedImgResult = 
/**  処理済み画像ファイル名 */
{ type: "Ok"; filename: string } | 
/**  現在処理が集中しているので、リトライしてほしい */
{ type: "Busy" } | 
/**  その他 (画像ではない、ファイルが読めないなど) */
{ type: "Fail"; error_msg: string };

/**  [`get_thumbnail()`](crate::commands::images::get_thumbnail) コマンドの結果 */
export type GetThumbnailResult = 
/**  サムネイル画像ファイル名 */
{ type: "Ok"; filename: string } | 
/**  現在処理が集中しているので、リトライしてほしい */
{ type: "Busy" } | 
/**  対象画像がない (ディレクトリの中に画像ファイルが見つからない) */
{ type: "NoImage" } | 
/**  その他 (画像ではない、ファイルが読めないなど) */
{ type: "Fail"; error_msg: string };

/**  プログラム起動 ([`invoke_program()`](crate::commands::app::invoke_program)) の結果 */
export type InvokeProgramResult = "Success" | { Fail: string };

/**  ファイルのカットかコピーか */
export type MoveOrCopy = { type: "Move" } | { type: "Copy" };

/**  ファイル削除 ([`remove_files()`](crate::commands::fs::remove_files)) の途中経過を通知するイベント構造体 */
export type RemoveFilesNotifyEvent = {
	task_id: number,
	head: TaskEventHeader,
	progress: TaskEventFileProgress,
};

/**  画像リサイズ時の画質設定 ([`AppPreferences`]の要素) */
export type ResizeImageConfig = {
	unsharp_sigma: number | null,
	unsharp_threshold: number,
};

/**  ファイル一覧のソート条件 (どの要素でソートするか＋昇順/降順) */
export type SortCondition = {
	sort_type: SortType,
	/**  昇順: true */
	asc: boolean,
};

/**  [`SortCondition`] の要素 */
export type SortType = 
/**  名前でソート */
{ type: "Name" } | 
/**  拡張子でソート */
{ type: "Ext" } | 
/**  ファイルサイズでソート */
{ type: "Size" } | 
/**  更新日時でソート */
{ type: "Time" };

/**  UIへ渡すタブ情報 */
export type TabInfoUI = {
	id: number,
	path: string,
};

export type TaskAnswer = 
/**  リネーム (file, dir) */
{ type: "Rename" } | 
/**  マージ (コピー時の dir) */
{ type: "Merge" } | 
/**  スキップ (file, dir) */
{ type: "Skip" } | 
/**  キャンセル */
{ type: "Cancel" };

/**  タスクの処理経過情報の共通情報 */
export type TaskEventFileProgress = {
	/**  トータルファイルサイズ */
	size: number,
	/**  ディレクトリ数 */
	dires: number,
	/**  ファイル数 */
	files: number,
	/**  シンボリックリンク数 */
	symlinks: number,
};

/**  Rust側で継続的に処理するタスクの進捗状況を通知するイベントの共通ヘッダー */
export type TaskEventHeader = {
	/**  Rust内部使用 */
	event_time_ms: number,
	/**  Rust内部使用 */
	event_count: number,
	/**  最後の通知かどうか */
	finished: boolean,
	/**  キャンセルされたかどうか (finished == true の場合) */
	canceled: boolean,
	/**  エラー発生時 (finished == true の場合) */
	error_msg: string | null,
};

/**  Task問い合わせの応答 */
export type TaskResponse = {
	answer: TaskAnswer,
	always: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

