import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import pluginReact from "eslint-plugin-react";
import reactCompiler from 'eslint-plugin-react-compiler';
import reactHooks from 'eslint-plugin-react-hooks';
import prettierConfig from 'eslint-config-prettier'
import { defineConfig } from "eslint/config";

export default defineConfig([
  pluginReact.configs.flat.recommended,
  reactHooks.configs.flat.recommended,
  reactCompiler.configs.recommended,
  tseslint.configs.recommended,
  {
    files: ["**/*.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
    plugins: { js },
    extends: ["js/recommended"],
    rules: {
      'react/react-in-jsx-scope': 'off',
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": "error",
    },
    settings: {
      React: {
        version: 'detect',
      }
    },
    languageOptions: { globals: globals.browser }
  },
  prettierConfig,
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'src-tauri/target/**',
      'src-tauri/gen/**',
      '*.config.js',
      '*.config.ts',
      'vite.config.ts',
      'src/lib/bindings.ts', // Auto-generated by tauri-specta
    ],
  },
]);
