use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::app;
    use crate::commands::fs;
    use crate::commands::migemo;

    Builder::<tauri::Wry>::new().commands(collect_commands![
        app::exit_app,
        app::init,
        fs::create_tab,
        fs::remove_tab,
        fs::get_tab_ids,
        fs::read_dir_entries,
        fs::get_dir_entries,
        fs::get_file_info,
        fs::sort_files,
        migemo::search_next_filename,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
#[allow(dead_code)]
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

// Windowsでこのテストが呼ばれると以下のエラーが発生するので無効にする
// ※ デバッグビルド実行時に lib.rs で呼ばれる bindings::export_ts_bindings() はエラーにならないので、bindings.ts は生成できる
//
// $ pnpm rust:bindings
// $ cd src-tauri && cargo test export_bindings --lib
//    Compiling comicviewerj3 v0.1.0 (C:\Users\xxx\Downloads\ComicViewerJ3\src-tauri)
//     Finished `test` profile [unoptimized + debuginfo] target(s) in 4.28s
//      Running unittests src\lib.rs (target\debug\deps\comicviewerj3_lib-51c14de9ef555d88.exe)
// error: test failed, to rerun pass `--lib`
//
// Caused by:
//   process didn't exit successfully: `C:\Users\xxx\Downloads\ComicViewerJ3\src-tauri\target\debug\deps\comicviewerj3_lib-51c14de9ef555d88.exe export_bindings` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
// note: test exited abnormally; to see the full output pass --no-capture to the harness.
// [ELIFECYCLE] Command failed with exit code 3221225785.
//
#[cfg(test)]
#[cfg(not(target_os = "windows"))]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
